//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: hello

package hello

import "github.com/google/flatbuffers/go"

import (
  context "golang.org/x/net/context"
  grpc "google.golang.org/grpc"
)

// Client API for Greeter service
type GreeterClient interface{
  Hello(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* Message, error)  
  HelloHello(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (Greeter_HelloHelloClient, error)  
}

type greeterClient struct {
  cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
  return &greeterClient{cc}
}

func (c *greeterClient) Hello(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* Message, error) {
  out := new(Message)
  err := grpc.Invoke(ctx, "/hello.Greeter/Hello", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

func (c *greeterClient) HelloHello(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (Greeter_HelloHelloClient, error) {
  stream, err := grpc.NewClientStream(ctx, &_Greeter_serviceDesc.Streams[0], c.cc, "/hello.Greeter/HelloHello", opts...)
  if err != nil { return nil, err }
  x := &greeterHelloHelloClient{stream}
  if err := x.ClientStream.SendMsg(in); err != nil { return nil, err }
  if err := x.ClientStream.CloseSend(); err != nil { return nil, err }
  return x,nil
}

type Greeter_HelloHelloClient interface {
  Recv() (*Message, error)
  grpc.ClientStream
}

type greeterHelloHelloClient struct{
  grpc.ClientStream
}

func (x *greeterHelloHelloClient) Recv() (*Message, error) {
  m := new(Message)
  if err := x.ClientStream.RecvMsg(m); err != nil { return nil, err }
  return m, nil
}

// Server API for Greeter service
type GreeterServer interface {
  Hello(context.Context, *Message) (*flatbuffers.Builder, error)  
  HelloHello(*Message, Greeter_HelloHelloServer) error  
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
  s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_Hello_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(Message)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(GreeterServer).Hello(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/hello.Greeter/Hello",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(GreeterServer).Hello(ctx, req.(* Message))
  }
  return interceptor(ctx, in, info, handler)
}


func _Greeter_HelloHello_Handler(srv interface{}, stream grpc.ServerStream) error {
  m := new(Message)
  if err := stream.RecvMsg(m); err != nil { return err }
  return srv.(GreeterServer).HelloHello(m, &greeterHelloHelloServer{stream})
}

type Greeter_HelloHelloServer interface { 
  Send(* flatbuffers.Builder) error
  grpc.ServerStream
}

type greeterHelloHelloServer struct {
  grpc.ServerStream
}

func (x *greeterHelloHelloServer) Send(m *flatbuffers.Builder) error {
  return x.ServerStream.SendMsg(m)
}


var _Greeter_serviceDesc = grpc.ServiceDesc{
  ServiceName: "hello.Greeter",
  HandlerType: (*GreeterServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "Hello",
      Handler: _Greeter_Hello_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
    {
      StreamName: "HelloHello",
      Handler: _Greeter_HelloHello_Handler, 
      ServerStreams: true,
    },
  },
}

